[versions]
agp = "8.13.2"
annotation = "1.9.1"
kotlin = "2.3.0"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2024.09.00"
ktx-coroutines = "1.10.2"
rikka-shizuku = "13.1.5"
rikka-refine = "4.4.0"
foundation = "1.10.0"
room = "2.8.4"
ksp = "2.3.0"
animation = "1.10.0"

[plugins]
toolchains-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version = "1.0.0" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
rikka-refine = { id = "dev.rikka.tools.refine", version.ref = "rikka-refine" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.9.6" }

compose-materialIcons = { group = "androidx.compose.material", name = "material-icons-extended", version = "1.7.8" }

ktx-coroutines_core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "ktx-coroutines" }
ktx-coroutines_android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "ktx-coroutines" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# AndroidHiddenApiBypass
# https://github.com/LSPosed/AndroidHiddenApiBypass
lsposed-hiddenapibypass = { group = "org.lsposed.hiddenapibypass", name = "hiddenapibypass", version = "6.1" }

rikka-refine-annotation-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "rikka-refine" }
rikka-refine-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "rikka-refine" }

# Koin Inject
# https://insert-koin.io/docs/setup/koin
koin-bom = { group = "io.insert-koin", name = "koin-bom", version = "4.1.1" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose" }

# Rikka Shizuku
# https://github.com/RikkaApps/Shizuku-API
rikka-shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "rikka-shizuku" }
rikka-shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "rikka-shizuku" }

# AndroidAppProcess
# https://github.com/iamr0s/AndroidAppProcess
iamr0s-androidAppProcess = { group = "io.github.iamr0s", name = "AndroidAppProcess", version = "1.4.2" }

# OpenAI Kotlin
# https://github.com/aallam/openai-kotlin
aallam-openai-bom = { module = "com.aallam.openai:openai-client-bom", version = "4.0.1" }
aallam-openai-client = { module = "com.aallam.openai:openai-client" }
ktor-client-okhttp = { module = 'io.ktor:ktor-client-okhttp' }

# LangChain4j
# https://docs.langchain4j.info/get-started
langchain4j-bom = { module = "dev.langchain4j:langchain4j-bom", version = "1.9.1" }
langchain4j-kotlin = { module = "dev.langchain4j:langchain4j-kotlin" }
langchain4j-openai = { module = "dev.langchain4j:langchain4j-open-ai" }
langchain4j-google-ai-gemini = { module = "dev.langchain4j:langchain4j-google-ai-gemini" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "animation" }
